services:
  db:
    image: postgres:alpine
    container_name: garbo_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=GarboDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garbo_app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AllowedHosts=${ALLOWED_HOSTS}
      - ConnectionStrings__sqlConnection=${ConnectionStrings__sqlConnection}
      - JwtSettings__validIssuer=${JWT_ISSUER}
      - JwtSettings__validAudience=${JWT_AUDIENCE}
      - JwtSettings__expires=${JWT_EXPIRES}
      - JwtSettings__secret=${JWT_SECRET}
      - EmailSettings__From=${EMAIL_FROM}
      - EmailSettings__SmtpServer=${SMTP_SERVER}
      - EmailSettings__Port=${EMAIL_PORT}
      - EmailSettings__Username=${EMAIL_USERNAME}
      - EmailSettings__Password=${EMAIL_PASSWORD}
      - AdminSettings__Email=${ADMIN_EMAIL}
      - AdminSettings__Password=${ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src/backend/Api/wwwroot/uploads:/app/wwwroot/uploads

volumes:
  postgres_data:
